Removing dependency on the configuration helpers in the iMAC scrips.

diff --git a/human_experiments/scripts/create_pupil_symlink b/human_experiments/scripts/create_pupil_symlink
--- a/human_experiments/scripts/create_pupil_symlink
+++ b/human_experiments/scripts/create_pupil_symlink
@@ -2,18 +2,10 @@
 
 set -u
 
-source configuration_helpers
-
 if [[ -z ${1+x} ]]; then
   TARGET_DIR=""
 else
   TARGET_DIR=$1
-fi
-
-if [[ -z ${2+x} ]]; then
-  PADDING=""
-else
-  PADDING=$2
 fi
 
 # Local directory where pupil data is saved in the client machines
@@ -21,13 +13,15 @@ PUPIL_RECORDER_LOCAL_DIR="$HOME/recordings/$(date +%Y_%m_%d)"
 
 # Remove any previous link that might exist
 if [[ -d "$PUPIL_RECORDER_LOCAL_DIR" ]]; then
-  unlink "$PUPIL_RECORDER_LOCAL_DIR"
+  if ! unlink "$PUPIL_RECORDER_LOCAL_DIR"; then
+    echo "The directory $PUPIL_RECORDER_LOCAL_DIR is not a symbolic link."
+    exit 1
+  fi
 fi
 
-if ln -s "$TARGET_DIR" "$PUPIL_RECORDER_LOCAL_DIR"; then
-  echo -e "${PADDING}${GREEN}Symbolic link ${EMPH}$TARGET_DIR -> $PUPIL_RECORDER_LOCAL_DIR${GREEN} successfully created.${NC}"
-  exit 0
-else
-  echo -e "${PADDING}${RED}Failed to create symbolic link ${EMPH}$TARGET_DIR -> $PUPIL_RECORDER_LOCAL_DIR${RED}.${NC}"
+if ! ln -s "$TARGET_DIR" "$PUPIL_RECORDER_LOCAL_DIR"; then
+  echo "Failed to create symbolic link $TARGET_DIR -> $PUPIL_RECORDER_LOCAL_DIR."
   exit 1
 fi
+
+exit 0
diff --git a/human_experiments/scripts/remove_pupil_symlink b/human_experiments/scripts/remove_pupil_symlink
--- a/human_experiments/scripts/remove_pupil_symlink
+++ b/human_experiments/scripts/remove_pupil_symlink
@@ -2,15 +2,7 @@
 
 set -u
 
-source configuration_helpers
-
 # This script must be executed in the client side.
-
-if [[ -z ${1+x} ]]; then
-  PADDING=""
-else
-  PADDING=$1
-fi
 
 # Local directory where pupil data is saved in the client machines
 PUPIL_RECORDER_LOCAL_DIR="$HOME/recordings/$(date +%Y_%m_%d)"
@@ -18,6 +10,9 @@ PUPIL_RECORDER_LOCAL_DIR="$HOME/recordings/$(date +%Y_%m_%d)"
 # Remove a previous link that might exist
 if [[ -d "$PUPIL_RECORDER_LOCAL_DIR" ]]; then
   if ! unlink "$PUPIL_RECORDER_LOCAL_DIR"; then
-    echo -e "${PADDING}${RED}Failed to remove the symbolic link ${EMPH}$PUPIL_RECORDER_LOCAL_DIR${RED}.${NC}"
+    echo "Failed to remove the symbolic link $PUPIL_RECORDER_LOCAL_DIR."
+    exit 1
   fi
 fi
+
+exit 0
