Adding port forward call to the uber script.

diff --git a/human_experiments/scripts/end_experiment b/human_experiments/scripts/end_experiment
--- a/human_experiments/scripts/end_experiment
+++ b/human_experiments/scripts/end_experiment
@@ -92,6 +92,30 @@ __stop_minecraft() {
   done
 }
 
+__stop_port_forwarding() {
+  local client_name=$1
+  local client_address=$2
+  local padding=$3
+
+  local pid_path="$EXPERIMENT_DIR/tmp/${client_name}_port_forwarding.pid"
+  local pid
+  pid=$(cat "$pid_path")
+
+  echo -e "${padding}Stopping port forwarding..."
+  local stopped="n"
+  while [[ $stopped != "y" ]]; do
+    if ssh "$EXPERIMENT_USER@$client_address" "kill $pid" > /dev/null; then
+      echo -e "${padding}${GREEN} Port forwarding successfully stopped.${NC}"
+    else
+      echo -e "${padding}${RED} Failed to stop port forwarding.${NC}"
+      yes_no_question "${padding} Do you want to ${EMPH}RETRY${NC}?"
+      if [[ $? -ne 0 ]]; then
+        break
+      fi
+    fi
+  done
+}
+
 __close_application() {
   local client_name=$1
   local client_address=$2
@@ -169,6 +193,7 @@ __cleanup_on_client() {
     __stop_face_and_screen_recording "$client_name" "$client_address" "$padding "
     __stop_audio_streamer "$client_name" "$client_address" "$padding "
     __stop_minecraft "$client_name" "$client_address" "$padding "
+    __stop_port_forwarding "$client_name" "$client_address" "$padding "
     __close_applications "$client_name" "$client_address" "$padding "
     __remove_pupil_symlink "$client_name" "$client_address" "$padding "
     __close_extra_desktops "$client_name" "$client_address" "$padding "
