Killing all instances of minecraft

diff --git a/human_experiments/scripts/end_experiment b/human_experiments/scripts/end_experiment
--- a/human_experiments/scripts/end_experiment
+++ b/human_experiments/scripts/end_experiment
@@ -9,7 +9,7 @@ source configuration_helpers
 if [[ -z ${1+x} ]]; then
   # In case the script is executed standalone.
   text="${RED}Please provide an experiment directory as the first argument of "
-  text+="the call to this script."
+  text+="the call to this script.${NC}"
   echo -e "$text"
   exit 1
 fi
@@ -49,33 +49,24 @@ __stop_minecraft() {
   local client_address=$2
   local padding=$3
 
-  local pid_filepath=$EXPERIMENT_DIR/tmp/minecraft_$client_name.pid
-  if [[ -e "$pid_filepath" ]]; then
-    local minecraft_pid=$(cat $pid_filepath)
+  local command="cd \$HOME/$SYSTEMS_DIR/tomcat/human_experiments/scripts/ && "
+  command+="./kill_minecraft \"$padding \""
 
-    local command="cd \$HOME/$SYSTEMS_DIR/tomcat/human_experiments/scripts/ && "
-    command+="./kill_minecraft $minecraft_pid \"$padding \""
-
-    echo -e "${padding}Stopping ${EMPH}Minecraft${NC}..."
-    local stopped="n"
-    while [[ $stopped != "y" ]]; do
-      ssh $EXPERIMENT_USER@$client_address "$command"
-      if [[ $? -eq 0 ]]; then
-        echo -e "${padding}${GREEN} ${EMPH}Minecraft${GREEN} successfully stopped."
-        stopped="y"
-      else
-        echo -e "${padding}${RED} Failed to stop ${EMPH}Minecraft${NC}."
-        yes_no_question "${padding} Do you want to ${EMPH}RETRY${RED}?"
-        if [[ $? -ne 0 ]]; then
-          break
-        fi
+  echo -e "${padding}Stopping ${EMPH}Minecraft${NC}..."
+  local stopped="n"
+  while [[ $stopped != "y" ]]; do
+    ssh $EXPERIMENT_USER@$client_address "$command"
+    if [[ $? -eq 0 ]]; then
+      echo -e "${padding}${GREEN} ${EMPH}Minecraft${GREEN} successfully stopped.${NC}"
+      stopped="y"
+    else
+      echo -e "${padding}${RED} Failed to stop ${EMPH}Minecraft${RED}.${NC}"
+      yes_no_question "${padding} Do you want to ${EMPH}RETRY${NC}?"
+      if [[ $? -ne 0 ]]; then
+        break
       fi
-    done
-  else
-    local text="${padding}${YELLOW}PID file ${EMPH}$pid_filepath${YELLOW} not "
-    text+="found for Minecraft on ${EMPH}$client_name${YELLOW}."
-    echo -e "$text"
-  fi
+    fi
+  done
 }
 
 __close_application() {
@@ -87,7 +78,7 @@ __close_application() {
   local command="osascript \$HOME/$SYSTEMS_DIR/tomcat/human_experiments/scripts/macos/close_application.scpt "
   command+="\"$app_name\""
   ssh $EXPERIMENT_USER@$client_address "$command" &>/dev/null
-  echo -e "${padding}${GREEN}${EMPH}$app_name${GREEN} successfully closed."
+  echo -e "${padding}${GREEN}${EMPH}$app_name${GREEN} successfully closed.${NC}"
 
   # The apple script returns exit code 1 because closing an application is an
   # interruption. So, we do not check for a return code and assume the
@@ -121,10 +112,10 @@ __close_extra_desktops() {
   while [[ $closed != "y" ]]; do
     ssh $EXPERIMENT_USER@$client_address "$command" >/dev/null
     if [[ $? -eq 0 ]]; then
-      echo -e "${padding}${GREEN} ${EMPH}Extra desktops${GREEN} successfully closed."
+      echo -e "${padding}${GREEN} ${EMPH}Extra desktops${GREEN} successfully closed.${NC}"
       closed="y"
     else
-      echo -e "${padding}${RED} Failed to close ${EMPH}extra desktops${RED}."
+      echo -e "${padding}${RED} Failed to close ${EMPH}extra desktops${RED}.${NC}"
       yes_no_question "${padding} Do you want to ${EMPH}RETRY${NC}?"
       if [[ $? -ne 0 ]]; then
         break
@@ -162,10 +153,10 @@ __freeze_experiment_data() {
   while [[ $frozen != "y" ]]; do
     chmod a=r "$EXPERIMENT_DIR" >/dev/null
     if [[ $? -eq 0 ]]; then
-      echo -e "${padding}${GREEN} Data successfully frozen."
+      echo -e "${padding}${GREEN} Data successfully frozen.${NC}"
       frozen="y"
     else
-      echo -e "${padding}${RED} Failed to freeze data."
+      echo -e "${padding}${RED} Failed to freeze data.${NC}"
       yes_no_question "${padding} Do you want to ${EMPH}RETRY${NC}?"
       if [[ $? -ne 0 ]]; then
         break
@@ -178,7 +169,7 @@ __backup_experiment_data() {
   local padding=$1
 
   echo -e "${padding}${EMPH}Backing up${NC} data..."
-  echo -e "${padding}${YELLOW} Yet to be implemented!"
+  echo -e "${padding}${YELLOW} Yet to be implemented!${NC}"
 
   # TODO
   # here comes a call to Kobus' script to synchronize data between CAT, TOM
