.

diff --git a/human_experiments/scripts/extract_testbed_logs b/human_experiments/scripts/extract_testbed_logs
--- a/human_experiments/scripts/extract_testbed_logs
+++ b/human_experiments/scripts/extract_testbed_logs
@@ -12,27 +12,28 @@ echo -n -e "${PADDING}Please, enter the ${EMPH}Team Number${RED} for this experi
 read -r team_number
 
 pushd "$HOME/$SYSTEMS_DIR/testbed/Tools/docker-logs" >/dev/null || exit 1
-while true; do
-  if ./get_all_logs.sh -t "$team_number" | sed "s/^/${PADDING} /"; then
-    # Move the compressed logs to the experiment folder
-    mkdir -p "$EXPERIMENT_DIR/testbed_logs" >/dev/null
+  while true; do
+    if ./get_all_logs.sh -t "$team_number" | sed "s/^/${PADDING} /"; then
+      # Move the compressed logs to the experiment folder
+      mkdir -p "$EXPERIMENT_DIR/testbed_logs" >/dev/null
 
-    log_filename="$(find asist_logs_$team_number*.tar.gz)"
-    echo "$log_filename"
-    mv "$log_filename" "$EXPERIMENT_DIR/testbed_logs"
+      log_filename="$(find asist_logs_$team_number*.tar.gz)"
+      mv "$log_filename" "$EXPERIMENT_DIR/testbed_logs"
 
-    # Decompress file and remove compressed file
-    tar -xvzf "$EXPERIMENT_DIR/testbed_logs/$log_filename"
-    rm "$log_filename"
-
-    # Move vocalic features to the experiment folder
-    mv "$EXPERIMENT_DIR/testbed_logs/$log_filename/speech_analyzer_agent/features.sql" "$EXPERIMENT_DIR/vocalic_features.sql"
-    break
-  else
-    echo -e "${PADDING}${RED}Failed to extract the logs for the session. Make sure the testbed is up and retry.${NC}"
-    if ! yes_no_question "${PADDING}Do you want to ${EMPH}RETRY${NC}?"; then
-      break
+    else
+      echo -e "${PADDING}${RED}Failed to extract the logs for the session. Make sure the testbed is up and retry.${NC}"
+      if ! yes_no_question "${PADDING}Do you want to ${EMPH}RETRY${NC}?"; then
+        break
+      fi
     fi
-  fi
-done
+  done
 popd >/dev/null || exit 1
+
+pushd "$EXPERIMENT_DIR/testbed_logs" >/dev/null || exit 1
+  # Decompress file and remove compressed file
+  tar -xvzf "$EXPERIMENT_DIR/testbed_logs/$log_filename"
+  rm "$EXPERIMENT_DIR/testbed_logs/$log_filename"
+popd >/dev/null || exit 1
+
+
+
