Beautify (#343)
* Standardizing outputs

* Moving the client map step out of the minecraft step

* Creating options to the script

* Enabling option -a on all the steps.

* Fixing color

* Fix hanging after wifi is connected.

* Starting Minecraft with sudo on the server

* Killing all instances of minecraft

* Not lanuch minecraft as root and removing tailing ffmpeg log so the terminal can close.

* Commenting building lines in launchClient.sh

* Kills minecraft on the server side

Co-authored-by: Paulo Soares <paulosoares@SBS-7186.local>
Co-authored-by: Paulo Soares <paulosoares@dhcp-10-142-203-128.uawifi.arizona.edu>

diff --git a/human_experiments/scripts/open_client_map b/human_experiments/scripts/open_client_map
--- a/human_experiments/scripts/open_client_map
+++ b/human_experiments/scripts/open_client_map
@@ -25,11 +25,22 @@ __open_on_client() {
   local player_name=$3
   local padding=$4
 
-  yes_no_question "${padding}Do you want to open the client map on ${EMPH}$client_name?${NC}"
-  if [[ $? -eq 0 ]]; then
+  if [[ $ALL -ne 1 ]]; then
+    yes_no_question "${padding}Do you want to open the client map on ${EMPH}$client_name${NC}?"
+    ans=$?
+    padding="$padding "
+  fi
+  if [[ $ALL -eq 1 ]] || [[ $ans -eq 0 ]]; then
     # Open the client map
+    echo -e "${padding}Opening the ${EMPH}Client Map${NC} on ${EMPH}$client_name${NC}..."
+
     local command="osascript \$HOME/$SYSTEMS_DIR/tomcat/human_experiments/scripts/macos/open_client_map.scpt '$CLIENT_MAP_URL' $player_name"
-    ssh $EXPERIMENT_USER@$client_address "$command" > /dev/null
+    ssh $EXPERIMENT_USER@$client_address "$command" >/dev/null
+    if [[ $? -eq 0 ]]; then
+      echo -e "${padding} ${EMPH}Client Map${GREEN} opened successfully.${NC}"
+    else
+      echo -e "${padding} ${RED}Failed to open the ${EMPH}Client Map${RED}.${NC}"
+    fi
   fi
 }
 
@@ -37,7 +48,7 @@ __open_client_maps() {
   local padding=$1
 
   source collect_player_names "$EXPERIMENT_DIR" "$padding"
-  echo -e "${padding}Opening the ${EMPH}Client Maps...${NC}"
+  echo -e "${padding}Opening the ${EMPH}Client Maps${NC}..."
 
   __open_on_client "lion" "lion.local" $LION_PLAYER_NAME "$padding "
   __open_on_client "tiger" "tiger.local" $TIGER_PLAYER_NAME "$padding "
diff --git a/human_experiments/scripts/open_final_survey b/human_experiments/scripts/open_final_survey
--- a/human_experiments/scripts/open_final_survey
+++ b/human_experiments/scripts/open_final_survey
@@ -27,15 +27,24 @@ __open_on_client() {
   local player_name=$4
   local padding=$5
 
-  yes_no_question "${padding}Do you want to open the final survey on ${EMPH}$client_name?${NC}"
-  if [[ $? -eq 0 ]]; then
+  if [[ $ALL -ne 1 ]]; then
+    yes_no_question "${padding}Do you want to open the final survey on ${EMPH}$client_name${NC}?"
+    ans=$?
+    padding="$padding "
+  fi
+  if [[ $ALL -eq 1 ]] || [[ $ans -eq 0 ]]; then
     enable_wifi $client_name $client_address "$padding "
     wait_for_connection $client_name $client_address "$padding "
 
     # Open the survey
     local command="osascript \$HOME/$SYSTEMS_DIR/tomcat/human_experiments/scripts/macos/open_final_survey.scpt "
     command+="'$FINAL_SURVEY_URL' $participant_id $player_name $client_name"
-    ssh $EXPERIMENT_USER@$client_address "$command" > /dev/null
+    ssh $EXPERIMENT_USER@$client_address "$command" >/dev/null
+    if [[ $? -eq 0 ]]; then
+      echo -e "${padding}${EMPH}Final survey${GREEN} opened successfully.${NC}"
+    else
+      echo -e "${padding}${RED}Failed to open the ${EMPH}Final Survey${RED}.${NC}"
+    fi
   fi
 }
 
@@ -44,7 +53,7 @@ __open_final_surveys() {
 
   source collect_player_names "$EXPERIMENT_DIR" "$padding"
   source collect_participant_ids "$padding"
-  echo -e "${padding}Opening the ${EMPH}Final Survey...${NC}"
+  echo -e "${padding}Opening the ${EMPH}Final Survey${NC}..."
 
   __open_on_client "lion" "lion.local" $LION_PARTICIPANT_ID $LION_PLAYER_NAME "$padding "
   __open_on_client "tiger" "tiger.local" $TIGER_PARTICIPANT_ID $TIGER_PLAYER_NAME "$padding "
diff --git a/human_experiments/scripts/run_experiment b/human_experiments/scripts/run_experiment
--- a/human_experiments/scripts/run_experiment
+++ b/human_experiments/scripts/run_experiment
@@ -2,6 +2,58 @@
 
 set -u
 
+source configuration_helpers
+
+# This is the uber script that drives a full experiment. Each step of the
+# experimental design is included in form of questions, such that no
+# CS experience should be necessary to execute all the steps required.
+
+__help() {
+  # Display Help
+  echo
+  echo "This the Uber Script to run a complete experiment in the lab."
+  echo
+  echo "The steps are described below. The first step is always executed to "
+  echo "guarantee that data is saved to the correct directory. You can jump "
+  echo "to a specific step by setting the variable GOTO to the desired step "
+  echo "before calling the script (e.g. GOTO=5 ./run_experiment)"
+  echo
+  echo "[1]:  Set the experiment time"
+  echo "[2]:  Checks the NFS status"
+  echo "[3]:  Starts Mumble"
+  echo "[4]:  Starts fNIRS and Eye-tracker systems"
+  echo "[5]:  Starts Face and Screen recording"
+  echo "[6]:  Starts the Testbed"
+  echo "[7]:  Starts the Lab Recorder"
+  echo "[8]:  Starts the Baseline Tasks"
+  echo "[9]:  Starts Minecraft"
+  echo "[10]: Starts the Client Map"
+  echo "[11]: Opens the Final Survey"
+  echo "[12]: Ends the experiment (cleanup and backup phase)"
+  echo
+  echo "Syntax: run_experiment [-h|a]"
+  echo "options:"
+  echo "h     Print this Help."
+  echo "a     Starts the components in all of the client machines without "
+  echo "      asking the experimenter to confirm."
+  echo
+}
+
+ALL=0
+while getopts ":ha" option; do
+  case $option in
+    h) # display Help
+      __help
+      exit;;
+    a) # skip client confirmation
+      ALL=1
+      ;;
+    \?) # Invalid option
+      echo -e "${RED}Error: Invalid option"
+      exit;;
+  esac
+done
+
 data_dir_prefix_tom=/data/tom
 data_dir_prefix_cat=/data/cat
 
@@ -15,12 +67,11 @@ if [[ -z ${GOTO+x} ]]; then
   GOTO=2
 fi
 
-source configuration_helpers
 source check_global_variables
 source check_data_root_directory
 source check_connections
 
-echo -n -e "[1] Enter the experiment ${EMPH}time${NC}: "
+echo -n -e "[1] Enter the experiment ${EMPH}time${NC} (e.g. 09): "
 read -r experiment_time
 experiment_id=$(date +%Y_%m_%d_$experiment_time)
 
@@ -28,25 +79,25 @@ experiment_dir_tom=$data_dir_prefix_tom/$DATA_ROOT_DIR/exp_"$experiment_id"
 experiment_dir_cat=$data_dir_prefix_cat/$DATA_ROOT_DIR/exp_"$experiment_id"
 
 source create_data_directory_structure
-echo -e " Creating experiment directory structure for ${EMPH}TOM...${NC}"
+echo -e " Creating experiment ${EMPH}directory structure${NC} for ${EMPH}TOM${NC}..."
 create_data_directory_structure "$experiment_dir_tom" "  "
-echo -e " Creating experiment directory structure for ${EMPH}CAT...${NC}"
+echo -e " Creating experiment ${EMPH}directory structure${NC} for ${EMPH}CAT${NC}..."
 create_data_directory_structure "$experiment_dir_cat" "  "
 
 if [[ $GOTO -le 2 ]]; then
   echo " "
   yes_no_question "[2] Do you want to check ${EMPH}NFS${NC} status?"
   if [[ $? -eq 0 ]]; then
-    echo -e " Checking status for ${EMPH}TOM...${NC}"
+    echo -e " Checking ${EMPH}NFS${NC} status for ${EMPH}TOM${NC}..."
     source check_nfs $experiment_dir_tom "  "
-    echo -e " Checking status for ${EMPH}CAT...${NC}"
+    echo -e " Checking ${EMPH}NFS${NC} status for ${EMPH}CAT${NC}..."
     source check_nfs $experiment_dir_cat "  "
   fi
 fi
 
 if [[ $GOTO -le 3 ]]; then
   echo " "
-  yes_no_question "[3] Do you want to start ${EMPH}Mumble?${NC}"
+  yes_no_question "[3] Do you want to start ${EMPH}Mumble${NC}?"
   if [[ $? -eq 0 ]]; then
     source start_mumble " "
   fi
@@ -54,7 +105,7 @@ fi
 
 if [[ $GOTO -le 4 ]]; then
   echo " "
-  yes_no_question "[4] Do you want to start ${EMPH}fNIRS and Eye-tracker systems?${NC}"
+  yes_no_question "[4] Do you want to start ${EMPH}fNIRS and Eye-tracker systems${NC}?"
   if [[ $? -eq 0 ]]; then
     source start_sensors " "
   fi
@@ -62,7 +113,7 @@ fi
 
 if [[ $GOTO -le 5 ]]; then
   echo " "
-  yes_no_question "[5] Do you want to start ${EMPH}Face and Screen Recording?${NC}"
+  yes_no_question "[5] Do you want to start ${EMPH}Face and Screen Recording${NC}?"
   if [[ $? -eq 0 ]]; then
     source start_ffmpeg $experiment_dir_cat " "
   fi
@@ -70,7 +121,7 @@ fi
 
 if [[ $GOTO -le 6 ]]; then
   echo " "
-  yes_no_question "[6] Do you want to start the ${EMPH}Testbed?${NC}"
+  yes_no_question "[6] Do you want to start the ${EMPH}Testbed${NC}?"
   if [[ $? -eq 0 ]]; then
     source start_testbed $experiment_dir_cat " "
   fi
@@ -78,7 +129,7 @@ fi
 
 if [[ $GOTO -le 7 ]]; then
   echo " "
-  yes_no_question "[7] Do you want to start ${EMPH}Lab Recorder?${NC}"
+  yes_no_question "[7] Do you want to start ${EMPH}Lab Recorder${NC}?"
   if [[ $? -eq 0 ]]; then
     source start_lab_recorder $experiment_dir_cat " "
   fi
@@ -86,7 +137,7 @@ fi
 
 if [[ $GOTO -le 8 ]]; then
   echo " "
-  yes_no_question "[8] Do you want to start the ${EMPH}Baseline Tasks?${NC}"
+  yes_no_question "[8] Do you want to start the ${EMPH}Baseline Tasks${NC}?"
   if [[ $? -eq 0 ]]; then
     source start_baseline_tasks $experiment_dir_cat " "
   fi
@@ -94,26 +145,34 @@ fi
 
 if [[ $GOTO -le 9 ]]; then
   echo " "
-  yes_no_question "[9] Do you want to start ${EMPH}Minecraft?${NC}"
+  yes_no_question "[9] Do you want to start ${EMPH}Minecraft${NC}?"
   if [[ $? -eq 0 ]]; then
     source start_minecraft $experiment_dir_cat " "
+  fi
+fi
+
+if [[ $GOTO -le 10 ]]; then
+  echo " "
+  yes_no_question "[10] Do you want to open the ${EMPH}Client Map${NC}?"
+  if [[ $? -eq 0 ]]; then
+    source open_client_map $experiment_dir_cat " "
   fi
 fi
 
 # TODO - Place client map phase here out of the minecraft script
 # TODO - Open Minecraft on the server
 
-if [[ $GOTO -le 10 ]]; then
+if [[ $GOTO -le 11 ]]; then
   echo " "
-  yes_no_question "[10] Do you want to open the ${EMPH}Final Survey?${NC}"
+  yes_no_question "[11] Do you want to open the ${EMPH}Final Survey${NC}?"
   if [[ $? -eq 0 ]]; then
     source open_final_survey $experiment_dir_cat " "
   fi
 fi
 
-if [[ $GOTO -le 11 ]]; then
+if [[ $GOTO -le 12 ]]; then
   echo " "
-  text="[11] Type [${EMPH}quit${NC}] to end the experiment and close "
+  text="[12] Type [${EMPH}quit${NC}] to end the experiment and close "
   text+="all open applications and processes: "
   wait_for_key "$text" "quit"
   source end_experiment $experiment_dir_cat " "
diff --git a/human_experiments/scripts/start_mumble b/human_experiments/scripts/start_mumble
--- a/human_experiments/scripts/start_mumble
+++ b/human_experiments/scripts/start_mumble
@@ -5,9 +5,9 @@ set -u
 source configuration_helpers
 
 if [[ -z ${1+x} ]]; then
-  padding=""
+  PADDING=""
 else
-  padding=$1
+  PADDING=$1
 fi
 
 __start_mumble_on_client() {
@@ -15,21 +15,31 @@ __start_mumble_on_client() {
   local client_address=$2
   local padding=$3
 
-  yes_no_question "${padding}Do you want to start Mumble on ${EMPH}$client_name?${NC}"
-  if [[ $? -eq 0 ]]; then
+  if [[ $ALL -ne 1 ]]; then
+    yes_no_question "${padding}Do you want to start ${EMPH}Mumble${NC} on ${EMPH}$client_name${NC}?"
+    ans=$?
+    padding="$padding "
+  fi
+  if [[ $ALL -eq 1 ]] || [[ $ans -eq 0 ]]; then
     # Start Mumble in a new desktop in the client machines
+    echo -e "${padding}Opening ${EMPH}Mumble${NC} on ${EMPH}$client_name${NC}..."
     create_new_desktop_on_client $client_address
-    ssh $EXPERIMENT_USER@$client_address "open -a Mumble"
+    ssh $EXPERIMENT_USER@$client_address "open -a Mumble" >/dev/null
+    if [[ $? -eq 0 ]]; then
+      echo -e "${padding} ${EMPH}Mumble${GREEN} successfully launched.${NC}"
+    else
+      echo -e "${padding} ${RED}Failed to launch the ${EMPH}Mumble${RED}.${NC}"
+    fi
   fi
 }
 
-__start_mumble_on_client "lion" "lion.local" "$padding"
-__start_mumble_on_client "tiger" "tiger.local" "$padding"
-__start_mumble_on_client "leopard" "leopard.local" "$padding"
+__start_mumble_on_client "lion" "lion.local" "$PADDING"
+__start_mumble_on_client "tiger" "tiger.local" "$PADDING"
+__start_mumble_on_client "leopard" "leopard.local" "$PADDING"
 
 # The applescript does not work on the mumble interface and there's no
 # available command-line option to establish the connection programmatically.
 # Therefore, the process has to be done manually using a remote desktop client.
-text="${padding}${YELLOW}Use ${EMPH}Remmina${YELLOW} to connect the client "
-text+="machines to the server in the Mumble interface.${NC}"
+text="${PADDING}${YELLOW}Use ${EMPH}Remmina${YELLOW} to connect the client "
+text+="machines to the server in the ${EMPH}Mumble${YELLOW} interface.${NC}"
 echo -e "$text"
