Updating uber script

diff --git a/human_experiments/scripts/pupil_recording b/human_experiments/scripts/pupil_recording
--- a/human_experiments/scripts/pupil_recording
+++ b/human_experiments/scripts/pupil_recording
@@ -13,7 +13,7 @@ else
   padding=$2
 fi
 
-if [[ "$action" != "open" ]] && [[ "$action" != "start" ]] && [[ "$action" != "stop" ]]; then
+if [[ "$action" != "open" && "$action" != "close" && "$action" != "start" && "$action" != "stop" ]]; then
   echo -e "${RED}{$padding}The second parameter os this script must be a action form the list [start, stop].${NC}"
 fi
 
@@ -94,50 +94,6 @@ _stop_on_client() {
       fi
     done
     popd >/dev/null || exit
-
-    local project_dir="\$HOME/$SYSTEMS_DIR/tomcat"
-
-    # Closing the program
-    local exec_path="$project_dir/human_experiments/scripts/local/close_pupil_program"
-    local command="$exec_path"
-
-    # shellcheck disable=SC2029
-    while true; do
-      if ssh "$EXPERIMENT_USER@$client_address" "$command"; then
-        # Wait a bit before proceeding.
-        sleep 1
-        echo -e "${padding}${GREEN}Closed Pupil Capture${NC}"
-        break
-      else
-        echo -e "${padding}${RED}Could not close Pupil Capture.${NC}"
-        retry_question "$padding"
-        retry=$?
-
-        if [[ $retry -ne 0 ]]; then
-          break
-        fi
-      fi
-    done
-
-    # Remove symbolic link
-    while true; do
-      local exec_path="$project_dir/human_experiments/scripts/local/remove_pupil_symlink"
-      local command="$exec_path"
-
-      # shellcheck disable=SC2029
-      if ssh "$EXPERIMENT_USER@$client_address" "$command"; then
-        echo -e "${padding}${GREEN}Symlink removed${NC}"
-        break
-      else
-        echo -e "${padding}${RED}Could not remove symlink.${NC}"
-        retry_question "$padding"
-        retry=$?
-
-        if [[ $retry -ne 0 ]]; then
-          break
-        fi
-      fi
-    done
   fi
 }
 
@@ -212,29 +168,97 @@ _open_on_client() {
   fi
 }
 
+_close_on_client() {
+  # Just opens the program on a client machine and leaves. It does not wait for status.
+  local client_name=$1
+  local client_address=$2
+  local padding=$3
+
+  if [[ $ALL -ne 1 ]]; then
+    yes_no_question "${padding}Do you want to close Pupil Capture on ${EMPH}$client_name${NC}?"
+    ans=$?
+    padding="$padding "
+  fi
+  if [[ $ALL -eq 1 ]] || [[ $ans -eq 0 ]]; then
+    local project_dir="\$HOME/$SYSTEMS_DIR/tomcat"
+
+    # Closing the program
+    local exec_path="$project_dir/human_experiments/scripts/local/close_pupil_program"
+    local command="$exec_path"
+
+    # shellcheck disable=SC2029
+    while true; do
+      if ssh "$EXPERIMENT_USER@$client_address" "$command"; then
+        # Wait a bit before proceeding.
+        sleep 1
+        echo -e "${padding}${GREEN}Closed Pupil Capture${NC}"
+        break
+      else
+        echo -e "${padding}${RED}Could not close Pupil Capture.${NC}"
+        retry_question "$padding"
+        retry=$?
+
+        if [[ $retry -ne 0 ]]; then
+          break
+        fi
+      fi
+    done
+
+    # Remove symbolic link
+    while true; do
+      local exec_path="$project_dir/human_experiments/scripts/local/remove_pupil_symlink"
+      local command="$exec_path"
+
+      # shellcheck disable=SC2029
+      if ssh "$EXPERIMENT_USER@$client_address" "$command"; then
+        echo -e "${padding}${GREEN}Symlink removed${NC}"
+        break
+      else
+        echo -e "${padding}${RED}Could not remove symlink.${NC}"
+        retry_question "$padding"
+        retry=$?
+
+        if [[ $retry -ne 0 ]]; then
+          break
+        fi
+      fi
+    done
+  fi
+}
+
 _open() {
   # Start at the same time in all clients
   _open_on_client "lion" "lion.local" "$padding"
-  #  _open_on_client "tiger" "tiger.local" "$padding"
-  #  _open_on_client "leopard" "leopard.local" "$padding"
+  _open_on_client "tiger" "tiger.local" "$padding"
+  _open_on_client "leopard" "leopard.local" "$padding"
+}
+
+_close() {
+  # Close at the same time in all clients
+  _close_on_client "lion" "lion.local" "$padding"
+  _close_on_client "tiger" "tiger.local" "$padding"
+  _close_on_client "leopard" "leopard.local" "$padding"
 }
 
 _start_recording() {
   # Start at the same time in all clients
   _start_recording_on_client "lion" "lion.local" "$padding"
-  #  _start_recording_on_client "tiger" "tiger.local" "$padding"
-  #  _start_recording_on_client "leopard" "leopard.local" "$padding"
+  _start_recording_on_client "tiger" "tiger.local" "$padding"
+  _start_recording_on_client "leopard" "leopard.local" "$padding"
 }
 
 _stop_recording() {
   _stop_on_client "lion" "lion.local" "$padding"
-  #  _stop_record_on_client "tiger" "tiger.local" "$padding"
-  #  _stop_record_on_client "leopard" "leopard.local" "$padding"
+  _stop_on_client "tiger" "tiger.local" "$padding"
+  _stop_on_client "leopard" "leopard.local" "$padding"
 }
 
 if [[ "$action" == "open" ]]; then
   # Opens the programs and creates symbolic links
   _open "$padding"
+elif [[ "$action" == "close" ]]; then
+  # Closes the programs and removes symbolic links
+  _close "$padding"
 elif [[ "$action" == "start" ]]; then
   _start_recording "$padding"
 elif [[ "$action" == "stop" ]]; then
