Updating uber script

diff --git a/human_experiments/scripts/pupil_recording b/human_experiments/scripts/pupil_recording
--- a/human_experiments/scripts/pupil_recording
+++ b/human_experiments/scripts/pupil_recording
@@ -181,6 +181,20 @@ _open_on_client() {
       local target_dir="\$HOME/$EXPERIMENT_DIR/$client_name/pupil_recorder"
       local command="$exec_path $target_dir"
 
+      while true; do
+        if mkdir -p "$target_dir"; then
+          break
+        else
+          echo -e "${padding}${RED}Error when trying to create the folder ${target_dir}.${NC}"
+          retry_question "$padding"
+          retry=$?
+
+          if [[ $retry -ne 0 ]]; then
+            break
+          fi
+        fi
+      done
+
       # shellcheck disable=SC2029
       if ssh "$EXPERIMENT_USER@$client_address" "$command"; then
         echo -e "${padding}${GREEN}Program successfully opened and symlink created.${NC}"
