Added configuration and refactored up to eye-tracker part.

diff --git a/human_experiments/scripts/run_experiment_wrap b/human_experiments/scripts/run_experiment_wrap
--- a/human_experiments/scripts/run_experiment_wrap
+++ b/human_experiments/scripts/run_experiment_wrap
@@ -1,199 +1,233 @@
 #!/bin/bash
 
+# This is the uber script that drives a full experiment. Each step of the experimental design is included in form of
+# questions, such that no CS experience should be necessary to execute all the steps required.
+# If anything goes wrong during the experiment, the experimenter can abort the process, fix the issue and later
+# start over by jumping to a specific step in the experiment.
+
 set -u
 
-source configuration_helpers
+CONFIG_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/../config/uber_script" >/dev/null 2>&1 && pwd)"
+SCRIPTS_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" >/dev/null 2>&1 && pwd)"
+export SCRIPTS_DIR
 
-# This is the uber script that drives a full experiment. Each step of the
-# experimental design is included in form of questions, such that no
-# CS experience should be necessary to execute all the steps required.
+# Load global variables for the experiment
+source "$CONFIG_DIR/config"
 
-__help() {
-  # Display Help
-  echo
-  echo "This the Uber Script to run a complete experiment in the lab."
-  echo
-  echo "The steps are described below. The first step is always executed to "
-  echo "guarantee that data is saved to the correct directory. You can jump "
-  echo "to a specific step by setting the variable GOTO to the desired step "
-  echo "before calling the script (e.g. GOTO=5 ./run_experiment)"
-  echo
-  echo "[1]:  Set the experiment time"
-  echo "[2]:  Checks the NFS status"
-  echo "[3]:  Starts Eye-tracker"
-  echo "[4]:  Starts the Testbed"
-  echo "[5]:  Starts the Lab Recorder"
-  echo "[6]:  Starts Face and Screen recording"
-  echo "[7]:  Starts the Baseline Tasks"
-  echo "[8]:  Plays Instructive Video"
-  echo "[9]:  Starts Minecraft"
-  echo "[10]: Opens the Client Map"
-  echo "[11]: Starts the Audio Streamer"
-  echo "[12]: Opens the Final Survey"
-  echo "[13]: Stops the LabRecorder recordings and kill the LabRecorder instances on CAT"
-  echo "[14]: Exports Minecraft data"
-  echo "[15]: Ends the experiment (cleanup and backup phase)"
-  echo
-  echo "Syntax: run_experiment [-h|a]"
-  echo "options:"
-  echo "h     Print this Help."
-  echo "a     Starts the components in all of the client machines without "
-  echo "      asking the experimenter to confirm."
-  echo
-}
-
-ALL=0
-while getopts ":ha" option; do
-  case $option in
-    h) # display Help
-      __help
-      exit;;
-    a) # skip client confirmation
-      ALL=1
-      ;;
-    \?) # Invalid option
-      echo -e "${RED}Error: Invalid option"
-      exit;;
-  esac
-done
-export ALL
-
-data_dir_prefix_cat=/data/cat
-if [[ -z ${DEVELOP+x} ]]; then
-  export DEVELOP=0
+# Get the link to the final survey from the internal resources
+if [ -f "$FINAL_SURVEY_LINK_PATH" ];then
+    # shellcheck disable=SC1090
+    source "$FINAL_SURVEY_LINK_PATH"
 fi
 
-if [[ -z ${GOTO+x} ]]; then
-  # The step to jump to after the first step. If not provided, it starts from
-  # the next step after the first one.
-  GOTO=2
-fi
+# Export variables in the config file that can be used by sub-processes.
+export SYSTEMS_DIR
+export EXPERIMENT_USER
+export CLIENT_MAP_URL
+export FINAL_SURVEY_URL
 
-source check_disk_space "$data_dir_prefix_cat"
-source check_global_variables
-source check_data_root_directory
-source check_connections
+pushd "$SCRIPTS_DIR" >/dev/null || exit 1
 
-echo -n -e "[1] Enter the experiment ${EMPH}time${NC} (e.g. 09): "
-read -r experiment_time
-experiment_id=$(date +%Y_%m_%d_"$experiment_time")
+  #source check_global_variables
+  source configuration_helpers
 
-experiment_dir_cat=$data_dir_prefix_cat/$DATA_ROOT_DIR/exp_"$experiment_id"
+  __help() {
+    # Display Help
+    echo
+    echo "This the Uber Script to run a complete experiment in the lab."
+    echo
+    echo "The steps are described below. The first step is always executed to "
+    echo "guarantee that data is saved to the correct directory. You can jump "
+    echo "to a specific step by setting the variable GOTO to the desired step "
+    echo "before calling the script (e.g. GOTO=5 ./run_experiment)"
+    echo
+    echo "[1]:  Set the experiment time"
+    echo "[2]:  Checks the NFS status"
+    echo "[3]:  Starts Eye-tracker"
+    echo "[4]:  Starts the Testbed"
+    echo "[5]:  Starts the Lab Recorder"
+    echo "[6]:  Starts Face and Screen recording"
+    echo "[7]:  Starts the Baseline Tasks"
+    echo "[8]:  Plays Instructive Video"
+    echo "[9]:  Starts Minecraft"
+    echo "[10]: Opens the Client Map"
+    echo "[11]: Starts the Audio Streamer"
+    echo "[12]: Opens the Final Survey"
+    echo "[13]: Stops the LabRecorder recordings and kill the LabRecorder instances on CAT"
+    echo "[14]: Exports Minecraft data"
+    echo "[15]: Ends the experiment (cleanup and backup phase)"
+    echo
+    echo "Syntax: run_experiment [-h|a]"
+    echo "options:"
+    echo "h     Print this Help."
+    echo "a     Starts the components in all of the client machines without "
+    echo "d     Dry-run mode. The data is saved under the dry-run directory structure."
+    echo "t     Test mode. The data is saved under the development directory structure. It has precedence over the -d option."
+    echo "      asking the experimenter to confirm."
+    echo
+  }
 
-source create_data_directory_structure
-echo -e " Creating experiment ${EMPH}directory structure${NC}..."
-create_data_directory_structure "$experiment_dir_cat" "  "
+  ALL=0
+  DRY_RUN=0
+  TEST=0
+  while getopts ":hadt" option; do
+    case $option in
+      h) # display Help
+        __help
+        exit;;
+      a) # skip client confirmation
+        ALL=1
+        ;;
+      d) # dry-run mode
+        DRY_RUN=1
+        ;;
+      t) # test mode
+        TEST=1
+        ;;
+      \?) # Invalid option
+        echo -e "${RED}Error: Invalid option"
+        exit;;
+    esac
+  done
+  export ALL
 
-if [[ $GOTO -le 2 ]]; then
-  echo " "
-  yes_no_question "[2] Do you want to check ${EMPH}NFS${NC} status?"
-  if [[ $? -eq 0 ]]; then
-    echo -e " Checking ${EMPH}NFS${NC} status for ${EMPH}CAT${NC}..."
-    source check_nfs "$experiment_dir_cat" "  "
+  if [[ $TEST -eq 1 ]]; then
+    DATA_ROOT_DIR="$DATA_DIR_TEST"
+    DRY_RUN=0
+  elif [[ $DRY_RUN -eq 1 ]]; then
+    DATA_ROOT_DIR="$DATA_DIR_DRY_RUN"
+  else
+    DATA_ROOT_DIR="$DATA_DIR_GROUP"
   fi
-fi
+  export DATA_ROOT_DIR
 
-if [[ $GOTO -le 3 ]]; then
-  echo " "
-  yes_no_question "[3] Do you want to start the ${EMPH}Eye-tracker${NC}?"
-  if [[ $? -eq 0 ]]; then
-    source start_sensors "$experiment_dir_cat" " "
+  # The step to jump to after the first step. If not provided, it starts from the next step after the first one.
+  if [[ -z ${GOTO+x} ]]; then
+    GOTO=2
   fi
-fi
 
-if [[ $GOTO -le 4 ]]; then
-  echo " "
-  yes_no_question "[4] Do you want to start the ${EMPH}Testbed${NC}?"
-  if [[ $? -eq 0 ]]; then
-    source start_testbed "$experiment_dir_cat" " "
+  source check_disk_space "$DATA_DIR"
+#  source check_connections
+  source check_data_root_directory
+
+  echo -n -e "[1] Enter the experiment ${EMPH}time${NC} (e.g. 09): "
+  read -r experiment_time
+  experiment_id=$(date +%Y_%m_%d_"$experiment_time")
+
+  export EXPERIMENT_DIR="$DATA_ROOT_DIR/exp_$experiment_id"
+
+  source create_data_directory_structure " "
+
+  if [[ $GOTO -le 2 ]]; then
+    echo " "
+
+    if yes_no_question "[2] Do you want to check ${EMPH}NFS${NC} status?"; then
+      source check_nfs "  "
+    fi
   fi
-fi
 
-if [[ $GOTO -le 5 ]]; then
-  echo " "
-  yes_no_question "[5] Do you want to start ${EMPH}Lab Recorder${NC}?"
-  if [[ $? -eq 0 ]]; then
-    source start_lab_recorder "$experiment_dir_cat" " "
+  if [[ $GOTO -le 3 ]]; then
+    echo " "
+    if yes_no_question "[3] Do you want to start the ${EMPH}Eye-tracker${NC}?"; then
+      source start_eye_tracker " "
+    fi
   fi
-fi
 
-if [[ $GOTO -le 6 ]]; then
-  echo " "
-  yes_no_question "[6] Do you want to start ${EMPH}Face and Screen Recording${NC}?"
-  if [[ $? -eq 0 ]]; then
-    source start_ffmpeg "$experiment_dir_cat" " "
+  if [[ $GOTO -le 4 ]]; then
+    echo " "
+    yes_no_question "[4] Do you want to start the ${EMPH}Testbed${NC}?"
+    if [[ $? -eq 0 ]]; then
+      source start_testbed "$experiment_dir_cat" " "
+    fi
   fi
-fi
 
-if [[ $GOTO -le 7 ]]; then
-  echo " "
-  yes_no_question "[7] Do you want to start the ${EMPH}Baseline Tasks${NC}?"
-  if [[ $? -eq 0 ]]; then
-    source start_baseline_tasks "$experiment_dir_cat" " "
+  if [[ $GOTO -le 5 ]]; then
+    echo " "
+    yes_no_question "[5] Do you want to start ${EMPH}Lab Recorder${NC}?"
+    if [[ $? -eq 0 ]]; then
+      source start_lab_recorder "$experiment_dir_cat" " "
+    fi
   fi
-fi
 
-if [[ $GOTO -le 8 ]]; then
-  echo " "
-  yes_no_question "[8] Do you want to play the ${EMPH}Instructive Video${NC}?"
-  if [[ $? -eq 0 ]]; then
-    source play_instructive_video " "
+  if [[ $GOTO -le 6 ]]; then
+    echo " "
+    yes_no_question "[6] Do you want to start ${EMPH}Face and Screen Recording${NC}?"
+    if [[ $? -eq 0 ]]; then
+      source start_ffmpeg "$experiment_dir_cat" " "
+    fi
   fi
-fi
 
-if [[ $GOTO -le 9 ]]; then
-  echo " "
-  yes_no_question "[9] Do you want to start ${EMPH}Minecraft${NC}?"
-  if [[ $? -eq 0 ]]; then
-    source start_minecraft "$experiment_dir_cat" " "
+  if [[ $GOTO -le 7 ]]; then
+    echo " "
+    yes_no_question "[7] Do you want to start the ${EMPH}Baseline Tasks${NC}?"
+    if [[ $? -eq 0 ]]; then
+      source start_baseline_tasks "$experiment_dir_cat" " "
+    fi
   fi
-fi
 
-if [[ $GOTO -le 10 ]]; then
-  echo " "
-  yes_no_question "[10] Do you want to open the ${EMPH}Client Map${NC}?"
-  if [[ $? -eq 0 ]]; then
-    source open_client_map "$experiment_dir_cat" " "
+  if [[ $GOTO -le 8 ]]; then
+    echo " "
+    yes_no_question "[8] Do you want to play the ${EMPH}Instructive Video${NC}?"
+    if [[ $? -eq 0 ]]; then
+      source play_instructive_video " "
+    fi
   fi
-fi
 
-if [[ $GOTO -le 11 ]]; then
-  echo " "
-  yes_no_question "[11] Do you want to start the ${EMPH}Audio Streamer${NC}?"
-  if [[ $? -eq 0 ]]; then
-    source start_audio_streamer "$experiment_dir_cat" " "
+  if [[ $GOTO -le 9 ]]; then
+    echo " "
+    yes_no_question "[9] Do you want to start ${EMPH}Minecraft${NC}?"
+    if [[ $? -eq 0 ]]; then
+      source start_minecraft "$experiment_dir_cat" " "
+    fi
   fi
-fi
 
-if [[ $GOTO -le 12 ]]; then
-  echo " "
-  yes_no_question "[12] Do you want to open the ${EMPH}Final Survey${NC}?"
-  if [[ $? -eq 0 ]]; then
-    source open_final_survey "$experiment_dir_cat" " "
+  if [[ $GOTO -le 10 ]]; then
+    echo " "
+    yes_no_question "[10] Do you want to open the ${EMPH}Client Map${NC}?"
+    if [[ $? -eq 0 ]]; then
+      source open_client_map "$experiment_dir_cat" " "
+    fi
   fi
-fi
 
-if [[ $GOTO -le 13 ]]; then
-  echo " "
-  yes_no_question "[13] Do you want to stop ${EMPH}LabRecorder recordings and kill the LabRecorder instances on CAT${NC}?"
-  if [[ $? -eq 0 ]]; then
-    source stop_lab_recorder
+  if [[ $GOTO -le 11 ]]; then
+    echo " "
+    yes_no_question "[11] Do you want to start the ${EMPH}Audio Streamer${NC}?"
+    if [[ $? -eq 0 ]]; then
+      source start_audio_streamer "$experiment_dir_cat" " "
+    fi
   fi
-fi
 
-if [[ $GOTO -le 14 ]]; then
-  echo " "
-  if yes_no_question "[14] Do you want to export ${EMPH}Minecraft data${NC} for all trials in the experiment?"; then
-    source export_minecraft_data "$experiment_dir_cat" " "
+  if [[ $GOTO -le 12 ]]; then
+    echo " "
+    yes_no_question "[12] Do you want to open the ${EMPH}Final Survey${NC}?"
+    if [[ $? -eq 0 ]]; then
+      source open_final_survey "$experiment_dir_cat" " "
+    fi
   fi
-fi
 
-if [[ $GOTO -le 15 ]]; then
-  echo " "
-  text="[15] Type [${EMPH}quit${NC}] to end the experiment and close "
-  text+="all open applications and processes: "
-  wait_for_key "$text" "quit"
-  source end_experiment "$experiment_dir_cat" " "
-fi
+  if [[ $GOTO -le 13 ]]; then
+    echo " "
+    yes_no_question "[13] Do you want to stop ${EMPH}LabRecorder recordings and kill the LabRecorder instances on CAT${NC}?"
+    if [[ $? -eq 0 ]]; then
+      source stop_lab_recorder
+    fi
+  fi
+
+  if [[ $GOTO -le 14 ]]; then
+    echo " "
+    if yes_no_question "[14] Do you want to export ${EMPH}Minecraft data${NC} for all trials in the experiment?"; then
+      source export_minecraft_data "$experiment_dir_cat" " "
+    fi
+  fi
+
+  if [[ $GOTO -le 15 ]]; then
+    echo " "
+    text="[15] Type [${EMPH}quit${NC}] to end the experiment and close "
+    text+="all open applications and processes: "
+    wait_for_key "$text" "quit"
+    source end_experiment "$experiment_dir_cat" " "
+  fi
+
+popd >/dev/null || exit 1
 
 exit 0
