Creating symbolic links for pupil capture and removing link in the end of the experiment.

diff --git a/human_experiments/scripts/start_sensors b/human_experiments/scripts/start_sensors
--- a/human_experiments/scripts/start_sensors
+++ b/human_experiments/scripts/start_sensors
@@ -25,8 +25,27 @@ __start_eye_tracker() {
   local client_address=$2
   local padding=$3
 
+  local target_dir="$EXPERIMENT_DIR/$client_name/pupil_recorder"
+
   echo -e "${padding}Starting ${EMPH}Eye-tracker${NC} on ${EMPH}$client_name${NC}..."
-  __start_sensor $client_address "launch_pupil_capture.scpt"
+  padding=" $padding"
+
+  # Creating destination folder in the server
+  mkdir target_dir
+  if [[ $? -ne 0 ]]; then
+    echo -e "${padding}${RED}Error when trying to create the folder ${target_dir}.${NC}"
+    exit 1
+  fi
+
+  # Creating a symbolic link between the local directory where recordings are stored and the directory in the server.
+  yes_no_question "${padding}Do you want to update the symbolic link to the experiment directory?"
+  if [[ $? -eq 0 ]]; then
+    local command="\$HOME/$SYSTEMS_DIR/tomcat/human_experiments/scripts/macos/create_pupil_symlink.sh "
+    command+="$target_dir \"$padding \""
+    ssh "$EXPERIMENT_USER"@"$client_address" "$command"
+  fi
+
+  __start_sensor "$client_address" "launch_pupil_capture.scpt"
   if [[ $? -eq 0 ]]; then
     echo -e "${padding}${GREEN} ${EMPH}Eye-tracker${GREEN} system successfully launched.${NC}"
   fi
