Message bus documentation and miscellaneous refactoring (#188)
Message bus documentation and miscellaneous refactoring
=======================================================

Documentation
-------------

- Added document (`docs/developer/architecture.rst`) on ToMCAT's architecture,
  that talks about its relationship with Malmo, the design philosophy, and some
  of the implemented 'sensors'.
- Added documentation on working with an MQTT message bus
  (`docs/developer/message_bus.rst`), added an example program to
  demonstrate working with `libmosquitto` under
  `src/cpp/examples/libmosquitto_example`, and a `FindMosquitto.cmake` find
  module to help build `libmosquitto_example` with CMake.
- Renamed `docs/developer/missions.md` to `docs/developer/missions.rst` to add
  links.
- Moved Java API pointer from `docs/index.rst` to `docs/developer/index.rst`
- Removed `.sh` suffix for some script names inside `docs/installation.md`

Refactoring
-----------

- Removed `src/cpp/WebcamSensor.*` files, since they are superseded by files in
  `src/cpp/faceSensor`
- Removed `src/cpp/LocalAgent.*` files, since they are superseded by the files
  in `src/cpp/model` (currently on the `model_v1_cpp` branch).
- Renamed the `runExperiment` executable to `runMission`, and moved the code
  for it under `src/cpp/runMission`. Additionally, `runMission` is now directly
  built from all the sources, rather than the intermediate `libtomcat.a` static
  library being built first and then linked to the `runMission` executable.
- Multiple `CMakeLists.txt` files have been cleaned up.
- All event and observations are now written to a single file, `messages.txt`,
  instead of being separated out into multiple files.
- Re-organized and renamed a few scripts under the `tools` directory. Notably,
  `autoformat_code`, `setup_shop3.sh`, and `upload_to_vanga` are now under
  `tools/dev`, and `download_TA3_world` and `download_openjdk8` are moved under
  the `tools/download` directory.

Removing support for Ubuntu 18.04
------------------------------------

This PR also removes support for automated installation of dependencies
and continuous integration for Ubuntu 18.04 - we require libmosquitto
1.5 or later, while the version available using apt on Ubuntu 18.04 is
1.4.15. Additionally, this should speed up continuous integration since
we would no longer have to install a number of libraries from source,
since the required versions would be available through apt.

We also add an option to skip automatic dependency installation, for
users on operating systems other than macOS and Ubuntu 20.04 who are
able to install the requirements themselves. Setting the environment
variable INSTALL_DEPENDENCIES to 0 will skip the automated installation
of dependencies (it is set to 1 by default).

diff --git a/tools/install_dependencies b/tools/install_dependencies
--- a/tools/install_dependencies
+++ b/tools/install_dependencies
@@ -78,6 +78,13 @@ __install_dependencies_using_apt() {
     echo ""
     echo "Installing dependencies using apt-get"
 
+    if [[ $DISTRO == ubuntu && $DISTRO_MAJOR_VERSION -lt 20 ]]; then
+        echo "Automatic installation of dependencies is only supported with"\
+             "Ubuntu 20.04 or later, since the required libraries are not available"\
+             "in recent enough versions using apt-get on earlier versions of Ubuntu."
+        exit 1
+    fi
+
     if ! sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test; then exit 1; fi
 
     if ! sudo apt-get update; then exit 1; fi
@@ -96,49 +103,18 @@ __install_dependencies_using_apt() {
         openssl \
         zlib1g-dev \
         libbz2-dev \
-        libyaml-cpp-dev
+        libyaml-cpp-dev \
+        libmosquitto-dev \
+        libboost-all-dev \
+        nlohmann-json3-dev \
+        libopencv-dev
     if [[ $? -ne 0 ]]; then exit 1; fi
 
-    # On Ubuntu 18.04 and older, the required version of the nlohmann-json JSON
-    # library is not available using apt-get, so we install from source.
-    if [[ $DISTRO == ubuntu && $DISTRO_MAJOR_VERSION -le 18 ]]; then
-        if ! "$TOMCAT"/tools/install_from_source/nlohmann-json; then
-            echo "Failed to install nlohmann-json from source."
-            exit 1
-        fi
-        # We do not install dlib from source on the Github Actions Ubuntu 18.04
-        # runner, since this causes timeouts.
-        if (( CI )); then
-            if ! "$TOMCAT"/tools/install_from_source/boost; then
-                echo "Failed to install Boost from source. Exiting now."
-                exit 1
-            fi
-
-        fi
-    else
-        if ! sudo apt install -y nlohmann-json3-dev; then
-            echo "Failed to install nlohmann-json3-dev using apt."
-            exit 1
-        fi
-
-        # The versions of dlib available using apt are not compatible with
-        # OpenCV 4, so we install the latest version from master.
-        if ! "$TOMCAT"/tools/install_from_source/dlib; then
-            echo "Failed to install dlib from source."
-            exit 1
-        fi
-
-
-        if ! sudo apt install -y libopencv-dev; then
-            echo "Failed to install libopencv-dev using apt."
-            exit 1
-        fi
-
-        # The Github Actions Ubuntu 18.04 VM already has Boost installed, but not
-        # all the components we need. So we will use apt-get to install the missing
-        # ones.
-        if ! sudo apt-get install -y libboost-all-dev; then exit 1; fi
-
+    # The versions of dlib available using apt are not compatible with
+    # OpenCV 4, so we install the latest version from master.
+    if ! "$TOMCAT"/tools/install_from_source/dlib; then
+        echo "Failed to install dlib from source."
+        exit 1
     fi
 }
 
