Revert "Trying to simplify OpenCV and dlib installation on Ubuntu 18.04"
This reverts commit 44c6bee11e9331141ca1954ad23ea5c630d03136.

diff --git a/tools/install_dependencies b/tools/install_dependencies
--- a/tools/install_dependencies
+++ b/tools/install_dependencies
@@ -113,14 +113,25 @@ __install_dependencies_using_apt() {
         fi
     fi
 
-    if ! sudo apt install -y libdlib-dev; then
-        echo "Failed to install dlib using apt."
+    if ! "$TOMCAT"/tools/install_from_source/dlib; then
+        echo "Failed to install dlib from source."
         exit 1
     fi
 
-    if ! sudo apt install -y libopencv-dev; then
-        echo "Failed to install libopencv-dev using apt."
-        exit 1
+    # We require a version of OpenCV that is newer than what is available via
+    # apt on Ubuntu 18.04 as of 2020/07/03. So we check the version of Ubuntu,
+    # and install OpenCV from source if the major version of Ubuntu is less
+    # than 20 (since OpenCV 4 is available via apt on Ubuntu Focal.
+    if [[ $DISTRO == ubuntu && $DISTRO_MAJOR_VERSION -ge 20 ]]; then
+        if ! sudo apt install -y libopencv-dev; then
+            echo "Failed to install libopencv-dev using apt."
+            exit 1
+        fi
+    else
+        if ! "$TOMCAT"/tools/install_from_source/opencv; then
+            echo "Failed to install OpenCV from source."
+            exit 1
+        fi
     fi
 
     # The Github Actions Ubuntu 18.04 VM already has Boost installed, but not
