Client side data encryption functionality added (script:data_encrypt). Modified install_dependencies to include openssl for Linux. Need to include install for Mac Ports. Upload session script modified to upload encrypted folder. Placed RSA public key in TOMCAT home folder.

diff --git a/tools/upload_session b/tools/upload_session
--- a/tools/upload_session
+++ b/tools/upload_session
@@ -11,7 +11,6 @@ export TOMCAT
 export TOMCAT_TMP_DIR="/tmp/$USER/tomcat"
 mkdir -p "${TOMCAT_TMP_DIR}"
 
-
 data_upload(){
 
     local session_id=$1
@@ -21,35 +20,50 @@ data_upload(){
     local participant_data_folder="${TOMCAT}/data/participant_data"
     local session_folder="${participant_data_folder}/${session_id}"
 
-    echo "Beginning data upload to vision server."
-
+	# First Create the zip file.
 
     # To maintain the directory structure and keep it simple, we cd into the
     # participant data folder and return back.
     pushd "$participant_data_folder" > /dev/null
-        if [[ ! -f "${session_folder}.zip" ]]; then
-            echo "Compressing session folder: ${session_folder}"
+
+        if [[ ! -f "${session_id}.zip" ]]; then
+            echo "Compressing encrypted session folder: ${session_id}"
             echo "This may take a minute ..."
-            if ! zip -q -r "${session_id}.zip" "$session_id"; then
+            if ! zip -q -r "${session_id}.zip" "${session_id}"; then
                 echo "Creation of zip file failed. Exiting now."
                 exit 1
             fi
         else
-            echo "${session_folder}.zip already exists!"
+            echo "${session_id}.zip already exists!"
             echo "We will attempt to upload it now."
         fi
     popd > /dev/null
 
+	# We can set an excryption flag and make this conditional.
+	# if DATA_ENCRYPT; then ....
+	if ! "$TOMCAT"/tools/data_encrypt "$session_id"; then 
+		echo "Data encryption failed. Exiting now."
+		exit 1
+	fi
+
+	# After data encryption script completes, we will obtain 
+	# encrypted zip file. ${session_folder}_encrypted.zip
+
+	local enc_zip_file="${session_folder}_encrypted.zip"
+
+    echo "Beginning data upload to vision server."
+
     curl_log="$TOMCAT_TMP_DIR"/vision_data_upload.log
-    if [[ -f "${session_folder}.zip" ]]; then
-        echo "Zip file created. Proceeding with data upload."
-        echo "Uploading data to vision server."
+
+    if [[ -f "${enc_zip_file}" ]]; then
+        echo "Encrypted zip file created. Proceeding with data upload."
+		echo "Uploading data to vision server. This may take a few mins ..."
     else
-        echo "Error: Failed to create zip file."
+        echo "Error: Failed to create encrypted file."
         exit 1
     fi
 
-    curl --netrc-file "$auth_file" -F "inputfile=@${session_folder}.zip"\
+    curl --netrc-file "$auth_file" -F "inputfile=@${session_folder}_encrypted.zip"\
         "$web_address" &> "$curl_log"
     if [[ $? -ne 0 ]]; then
         echo "The curl command to upload the data to the vision server "\
@@ -62,5 +76,6 @@ data_upload(){
 }
 
 data_upload $1
-
 exit 0
+# NOTE: Should include a cleanup script to handle errors and interrupts.
+# Clean up should take care of cleaning random keys and intermittent files generated.
